### ISSUE TITLE
MH202 Gateway support

### ISSUE THREAD

**Issue by matzfra** [jotonedev/pyown#33]
2025-03-16 14:30:19 [DEBUG] pyown.protocol: Sent message: *#13**15##
2025-03-16 14:30:19 [DEBUG] pyown.protocol: Received messages: [<DimensionResponse: 13,,15,200>, <ACK: #,1>]
Traceback (most recent call last):
  File "C:\dev\openwebnet\python\pyown\examples\gateway_01\main.py", line 79, in <module>
    main("10.0.0.XXX", 20000, "12345")
  File "C:\dev\openwebnet\python\pyown\examples\gateway_01\main.py", line 54, in main
    asyncio.run(run(host, port, password))
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\dev\openwebnet\python\pyown\examples\gateway_01\main.py", line 28, in run
    model = await gateway.get_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\items\gateway\gateway.py", line 300, in get_model
    return GatewayModel(resp.values[0].string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1171, in __new__
    raise ve_exc
ValueError: '200' is not a valid GatewayModel

Using MH202 https://catalogue.bticino.com/product/smart-home-solutions/my-home---home-automation-system/integration-and-control/BTI-MH202-EN

**Comment by jotonedev** [comment]
Issue solved. I will soon create a new release for the bug fix.

**Comment by matzfra** [comment]
thank you very much for your very quick response and fix!
tested it, now i getting another issue about datetime..

Traceback (most recent call last):
  File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 56, in <module>
    main(args.host, args.port, args.password)
  File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 34, in main
    asyncio.run(run(host, port, password))
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 22, in run
    await client.loop()
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\client\client.py", line 138, in loop
    await self._dispatch_callbacks(item, message)
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\client\client.py", line 151, in _dispatch_callbacks
    tasks = await item_obj.call_callbacks(item, message)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\items\gateway\gateway.py", line 525, in call_callbacks
    tasks += cls._create_tasks(callbacks, item, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Value after * must be an iterable, not datetime.datetime

**Comment by jotonedev** [comment]
> thank you very much for your very quick response and fix! tested it, now i getting another issue about datetime..
> 
> Traceback (most recent call last): File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 56, in main(args.host, args.port, args.password) File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 34, in main asyncio.run(run(host, port, password)) File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 22, in run await client.loop() File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\client\client.py", line 138, in loop await self._dispatch_callbacks(item, message) File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\client\client.py", line 151, in _dispatch_callbacks tasks = await item_obj.call_callbacks(item, message) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\items\gateway\gateway.py", line 525, in call_callbacks tasks += cls._create_tasks(callbacks, item, *args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: Value after * must be an iterable, not datetime.datetime

**Comment by jotonedev** [comment]
It should be fixed now in the new release 0.3.4
Please, if you can, test it and let me know 😉

**Comment by matzfra** [comment]
updated - but still getting the same error (examples\gateway_01\main.py works fine)

PS C:\dev\openwebnet\python\pyown\examples\gateway_02> python main.py
Traceback (most recent call last):
  File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 56, in <module>
    main(args.host, args.port, args.password)
  File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 34, in main
    asyncio.run(run(host, port, password))
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\dev\openwebnet\python\pyown\examples\gateway_02\main.py", line 22, in run
    await client.loop()
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\client\client.py", line 138, in loop
    await self._dispatch_callbacks(item, message)
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\client\client.py", line 151, in _dispatch_callbacks
    tasks = await item_obj.call_callbacks(item, message)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mf\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyown\items\gateway\gateway.py", line 525, in call_callbacks
    tasks += cls._create_tasks(callbacks, item, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Value after * must be an iterable, not datetime.datetime

**Comment by jotonedev** [comment]
I've noticed that I've never uploaded the newer release 🫠.
Please pull the latest commits from the repo and download the new release, and try again please.
